### PR TITLE
Prevent default phone account check when no SIM present

### PR DESCRIPTION
**Pull request by grit96**

### CODE REVIEW

**Comment by grit96** [comment]
At the moment if you run it on a device without a SIM, the setting to set the default calling account is missing and the `checkDefaultPhoneAccout` would always return false.

**Comment by manuquentin** [comment]
Hi !
I came to the same issue, the native phone app crashed when no SIM present on a Pixel 1 with Android 9 :
```
08-20 19:07:55.429  2960  2960 E Dialer  : SilentCrashReporter.uncaughtException - sendSilentFeedback
08-20 19:07:55.429  2960  2960 E Dialer  : java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.telephony.ServiceState.getState()' on a null object reference
08-20 19:07:55.429  2960  2960 E Dialer  : 	at czh.accept(Unknown Source:2)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at czy.a(Unknown Source:2)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at bxw.a(PG:3)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at kyd.run(PG:3)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at android.os.Handler.handleCallback(Handler.java:873)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at android.os.Looper.loop(Looper.java:193)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at android.app.ActivityThread.main(ActivityThread.java:6718)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at java.lang.reflect.Method.invoke(Native Method)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-20 19:07:55.429  2960  2960 E Dialer  : Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.telephony.ServiceState.getState()' on a null object reference
08-20 19:07:55.429  2960  2960 E Dialer  : 	at dau.a(PG:10)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at dau.a(PG:23)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at dau.a(PG:64)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at dat.call(Unknown Source:3)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at kzn.a(PG:1)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at kyl.run(PG:3)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at kzl.run(PG:2)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-20 19:07:55.429  2960  2960 E Dialer  : 	at java.lang.Thread.run(Thread.java:764)
```

Everything work with a SIM in the device.

With this PR the Phone app doesn't crash, but the phone account does not appear to be available :
Screenshot_20190820-133331

**Comment by kylekurz** [comment]
I've seen this same issue too, FYI. Haven't had time to dig into why it's a problem yet.

**Comment by manuquentin** [comment]
Merging as it's fix the crash, I'll open an issue with the disabled button

**Pull request merged**
