### PR TITLE
fix: init callKeepProvider asap

### LINKED ISSUE #311: *didLoadWithEvents* is not working.
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [x] iOS

## Description
Hi there, I'm facing the same issue as described in #107, and try to add ```didLoadWithEvents``` event right after ```RNCallkeep.setup()```; method. But the listener is not working.

## Steps to Reproduce

```js
  setUpCallKeep = () => {
    RNCallKeep.setup(callKeepOptions);
    RNCallKeep.setAvailable(true);
    RNCallKeep.addEventListener('didLoadWithEvents', (e) => {
      console.log('Navigation -> e', e);
    });
  };
```

this listener is not working even if the app was opened by call keep, nor when i accept or reject the call during the JS initialization.

## Versions
    - Callkeep:^3.1.1
    - React Native:0.63.1
    - iOS:13.5
    - Android: - 
    - Phone model: iPhone 7

### LINKED ISSUE #330: didLoadWithEvents always getting RNCallKeepDidDisplayIncomingCall
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] iOS

## Description
I have tried to register didLoadWithEvents in index.js and as well as App.js which is my first component. Both are returning RNCallKeepDidDisplayIncomingCall even if i press accept button right when callkit ui appears, i don't get acll accept event name here and if i press accept, i don't get answercall event either

## Versions
    - Callkeep: 4.0
    - React Native: 0.63.3
    - iOS: 14
    - Phone model: iPhone 7 

## Logs

```
Paste here
```

### LINKED ISSUE #347: Crash on sendEventWithNameWrapper didDeactivateAudioSession?
# Bug report

- [x ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [ x] iOS

## Description
This should be an easy one. When ending a call, my app crashes because the sendEventWithNameWrapper method crashes with:

```
'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
```

This is because the `body` argument passed in is nil.

Screenshot 2021-01-15 at 12 02 19

But this seems to be how it is invoked though: https://github.com/react-native-webrtc/react-native-callkeep/blob/master/ios/RNCallKeep/RNCallKeep.m#L766

## Steps to Reproduce
Start a call and then end it?

## Versions
    - Callkeep: 4.0.1
    - React Native: 0.63.4
    - iOS: 12.3
    - Android:
    - Phone model: iPhone 11

## Logs

```
2021-01-15 12:17:09.935296+0000 vTail[368:6649] [RNCallKeep][CXProviderDelegate][provider:didActivateAudioSession]
2021-01-15 12:17:10.106524+0000 vTail[368:6649] [RNCallKeep][configureAudioSession] Activating audio session
2021-01-15 12:17:13.501954+0000 vTail[368:6836] [RNCallKeep][endCall] uuidString = 7cf7a9db-a1f0-4025-93d8-da8fabad111f
2021-01-15 12:17:13.502594+0000 vTail[368:6836] [RNCallKeep][requestTransaction] transaction = <CXTransaction 0x2822d1ea0 UUID=6BEEF4C7-F7A8-4B1A-BA34-C29DBF5F5AD7 isComplete=0 actions=(
    "<CXEndCallAction 0x283748040 UUID=5D3D2904-D165-4BA6-A343-2F6C8835F6E0 state=0 commitDate=(null) callUUID=7CF7A9DB-A1F0-4025-93D8-DA8FABAD111F dateEnded=(null)>"
)>
2021-01-15 12:17:13.504321+0000 vTail[368:7148] [RNCallKeep][requestTransaction] Requested transaction successfully
2021-01-15 12:17:13.505895+0000 vTail[368:6649] [RNCallKeep][CXProviderDelegate][provider:performEndCallAction]
2021-01-15 12:17:13.775340+0000 vTail[368:7142] [aurioc] AURemoteIO.cpp:1598:Start: AUIOClient_StartIO failed (1701737535)
2021-01-15 12:17:13.798428+0000 vTail[368:6649] [RNCallKeep][CXProviderDelegate][provider:didDeactivateAudioSession]
2021-01-15 12:17:13.798807+0000 vTail[368:6649] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(0x189f9c878 0x19e4f2c50 0x18a00ce1c 0x18a019270 0x189e8d550 0x189e7fdd0 0x102501294 0x102506a8c 0x1a8b16360 0x1085bbbcc 0x1085bd6c0 0x1085ccf34 0x189f1811c 0x189f12120 0x189f1121c 0x1a0f90784 0x18c94a200 0x18c94fa74 0x10236902c 0x189bd16c0)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
terminating with uncaught exception of type NSException
```

### LINKED ISSUE #352: Getting crash while using RNCallKeep for outgoing call in iOS app
I am trying to integrate CallKit for outgoing and incoming calls. While making outgoing call with CallKit, it crashes iOS app. Code as below:

RNCallKeep.startCall(uuid, extension, extension, 'generic', false);

Here all params are passed in required format. Though it crashes and gives this error in Xcode:

int main(int argc, char * argv[]) {
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
  }
}

Error Log:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(0x1adb01114 0x1c1327cb4 0x1adb6b398 0x1adb76590 0x1ad9fc6a4 0x1ad9efa04 0x100b960c0 0x100b9b898 0x1cabddc80 0x1070efdb8 0x1070f15fc 0x1070ffa6c 0x1ada80c30 0x1ada7b0e8 0x1ada7a200 0x1c3b75598 0x1b0340004 0x1b03455d8 0x10068c264 0x1ad759598)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
terminating with uncaught exception of type NSException

### PR DESCRIPTION
**Pull request by Jerome91410**
1. If incoming call is answered before the `setup` method called from js, the event `RNCallKeepPerformAnswerCallAction` is never triggered. 
2. Init could be called more than once, so the `_delayedEvents` are cleared. 

fix #330 
fix #352 
fix #347
fix #311

### CODE REVIEW

**Comment by Jerome91410** [comment]
tested ok on iphone 8 (14.4)

**Comment by sboily** [comment]
Hello, thank you for your PR, is it ready for review?

**Comment by Jerome91410** [comment]
Currently, not ok on iphone XR:
`Termination Description: SPRINGBOARD, <RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-create watchdog transgression: application<com.xxxxx.xxxxxx>:2299 exhausted CPU time allowance of 4.93 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Background | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 23.470 (user 23.470, system 0.000), 43% CPU", | "Elapsed application CPU time (seconds): 5.222, 10% CPU" | ) reportType:CrashLog maxTerminationResistance:Interactive>
`

Investigation in progress.

If someone has any idea. :)

**Comment by Jerome91410** [comment]
seems to work fine my devices.

**Comment by stephanoparaskeva** [comment]
Works for me

**Comment by stephanoparaskeva** [comment]
Did not fix the issue for me

**Comment by manuquentin** [comment]
With this PR, I still have the callkit view displayed in background when I call `endCall`.
I don't reproduce the issue on the master branch

**Comment by Jerome91410** [comment]
> With this PR, I still have the callkit view displayed in background when I call `endCall`.
> I don't reproduce the issue on the master branch

Could you retest with the last commit?
I do not reproduce anymore with this fix.

**Comment by rcidt** [comment]
I tried this PR but it does not fix [my issue](https://github.com/react-native-webrtc/react-native-callkeep/issues/311#issuecomment-813116692)

**Comment by Romick2005** [comment]
Have you tried https://github.com/react-native-webrtc/react-native-callkeep/issues/330#issuecomment-799525290 this one also?

**Comment by rcidt** [comment]
I have tested this PR and it does fix #330.

Thanks @Jerome91410

**Pull request closed without merging**
