### PR TITLE
Improve type definitions

### LINKED ISSUE #680: error in getCalls type
https://github.com/react-native-webrtc/react-native-callkeep/blob/master/index.d.ts#L208

if we don't want to define the properties of the calls, it should at least not be `object` but an array

### PR DESCRIPTION
**Pull request by ramijarrar**
Fixes an error in my previous PR #657 with the 'didLoadWithEvents' handler.

Edit: Updated the PR (and squashed) with additional type fixes:

- Fix 'didReceiveStartCallAction' event payload

- Specify 'setSettings' and 'setForegroundServiceSettings' input shapes

- Fix 'getCalls' return type (closes #680 and #696)

### CODE REVIEW

**Comment by ramijarrar** [comment]
Have updated the PR to include an additional fix for the "didReceiveStartCallAction" payload type. This corrects the 'callUUID'/'name' fields to be optional (since callUUID will always be undefined on iOS and name can be undefined too).

**Comment by JasonWeinzierl** [comment]
If you're fixing types, could you also add the `emit` function too?  It's exported from `index.js` but not the types.

**Comment by ramijarrar** [comment]
@JasonWeinzierl I think it would make sense to create a separate PR for that which documents the method publicly as well as updating the types.

**Comment by ramijarrar** [comment]
Updated to fix 'getCalls' return type (resolves #680 and #696) and describe 'setSettings' / 'setForegroundServiceSettings' input shapes.

**Review by manuquentin — APPROVED** [review]

**Comment by manuquentin** [comment]
Thanks for the PR !

**Pull request merged**
