### PR TITLE
Pass attribute to ACTION_AUDIO_SESSION event

### LINKED ISSUE #101: didActivateAudioSession not being triggered on Android
This is due to `ACTION_AUDIO_SESSION` being sent with an attribute of `null`.

See `sendCallRequestToActivity(ACTION_AUDIO_SESSION, null);` [here](https://github.com/react-native-webrtc/react-native-callkeep/blob/46b9a488f737a002d73327847a8d8190f171754a/android/src/main/java/io/wazo/callkeep/VoiceConnection.java#L103) and [here](https://github.com/react-native-webrtc/react-native-callkeep/blob/28791bcd91880ad629fb55b9e5366e165ae76f9e/android/src/main/java/io/wazo/callkeep/VoiceConnectionService.java#L165).

This causes an issue due to a recent change to the `VoiceBroadcastReceiver.onReceive` that prevents the event being sent if the attribute is null [here](https://github.com/react-native-webrtc/react-native-callkeep/blob/master/android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java#L517).

### PR DESCRIPTION
**Pull request by grit96**
Fixes #101

### CODE REVIEW

**Comment by manuquentin** [comment]
This should be fixed [here](https://github.com/react-native-webrtc/react-native-callkeep/pull/98/files#diff-e7d3309b9e148681005f0c8fb53d185dL517). Can you test with this branch please ?

**Comment by grit96** [comment]
Thanks @manuquentin, it works on that branch.

**Comment by manuquentin** [comment]
Yes, soon :)

**Comment by manuquentin** [comment]
Released in `3.0.7`

**Pull request merged**
