### PR TITLE
Recreate Mark Corner's PR

### PR DESCRIPTION
**Pull request by kylekurz**
From #71

### CODE REVIEW

**Comment by manuquentin** [comment]
Thanks @kylekurz !

**Comment by sanjaypojo** [comment]
@danjenkins @manuquentin would it be possible to make a release? Would really like to use this feature. Thanks 😄

**Comment by manuquentin** [comment]
It's released in `3.0.11`.

**Comment by sanjaypojo** [comment]
Amazing, thanks a ton 🎉

**Pull request merged**
