### PR TITLE
Migrate to Android X

### PR DESCRIPTION
**Pull request by maximvoven**
Since V60.6 of react native android x is natively supported, this pull modernizes this library.
What Changes:
-Migrated to android Android X using jetifier
-Small change to build.gradle to get rid of warnings during compiling about build tools 
-Set compile api level to minimum for android play store.

### CODE REVIEW

**Comment by sboily** [comment]
Sound good to me.

**Comment by manuquentin** [comment]
Does it mean that it will not work with react-native <= `60.5` ? 
Should we maintain 2 versions: 3.xx for react-native > `60.5` and 2.xx for react-native <= `60.5` ?

**Comment by sboily** [comment]
Probably we could stop to maintain the 2.xx version, only the 3.xx with react-native > 60.5. Is there any objections to do that?

**Comment by manuquentin** [comment]
@maximvoven thanks for the PR !
Can you rebase it on master ?

**Comment by sboily** [comment]
@maximvoven can you rebase your branch for a merging please :) Thank you!

**Comment by maximvoven** [comment]
Branch is re-based and ready for merging, sorry about the delay

**Pull request merged**
