### PR TITLE
Set call active in android

### PR DESCRIPTION
**Pull request by german970814**
Fix for #236

### CODE REVIEW

**Comment by sboily** [comment]
Have you make test with the remark from #236? You need to call setCurrentCallActive(uuid). We don't understand why we will merge this PR.

**Comment by german970814** [comment]
Is there a reason not to make an active call after answering it?

**Comment by sboily** [comment]
@german970814 ohhh that's a very good question ;). We'll discuss with @manuquentin. But about video we need to add condition, there is no reason to enable video by default.

**Comment by german970814** [comment]
Give me some minutes to update it, because is a mistake

**Comment by manuquentin** [comment]
Hi @german970814 did you managed to update your PR with the removal of the default behaviour to video ?

**Comment by sboily** [comment]
Hello @german970814, can you update the PR :)? Thank you!

**Comment by rimonhanna** [comment]
@german970814

**Pull request closed without merging**
