### PR TITLE
ios: support additional options pass from js

### PR DESCRIPTION
**Pull request by zxcpoiu**
Continued from #188

### CODE REVIEW

**Comment by zxcpoiu** [comment]
I clean/remove the overloading functions of `reportNewIncomingCall`
There is no overloading api now

#### function arguments:

```objc
+ (void)reportNewIncomingCall:(NSString *)uuidString
                       handle:(NSString *)handle
                   handleType:(NSString *)handleType
                     hasVideo:(BOOL)hasVideo
          localizedCallerName:(NSString * _Nullable)localizedCallerName
              supportsHolding:(BOOL)supportsHolding
                 supportsDTMF:(BOOL)supportsDTMF
             supportsGrouping:(BOOL)supportsGrouping
           supportsUngrouping:(BOOL)supportsUngrouping
                  fromPushKit:(BOOL)fromPushKit
                      payload:(NSDictionary * _Nullable)payload
        withCompletionHandler:(void (^_Nullable)(void))completion
{
```

## Breaking change:

All user invoke this function in `AppDelegate.m` should now use:


```objc
    [RNCallKeep reportNewIncomingCall: uuidString
                               handle: handle
                           handleType: handleType
                             hasVideo: YES
                  localizedCallerName: localizedCallerName
                      supportsHolding: YES
                         supportsDTMF: YES
                     supportsGrouping: YES
                   supportsUngrouping: YES
                          fromPushKit: YES
                              payload: nil
                withCompletionHandler: nil];
```

#### or one line version

```objc
[RNCallKeep reportNewIncomingCall:uuidString handle:handle handleType:handleType hasVideo:YES localizedCallerName:localizedCallerName supportsHolding:YES supportsDTMF:YES supportsGrouping:YES supportsUngrouping:YES fromPushKit:YES payload:nil withCompletionHandler:nil];
```

**Comment by sboily** [comment]
Hello, Android support some of features like iOS did for example video support, hold, maybe grouping is conference (need to check) etc ... I don't know if we update this PR and merge this one and create new one for Android.

**Comment by zxcpoiu** [comment]
I think if this PR does not conflict with master or other WIP PR, it's better to merge this first, then create a new one for android option, once the android  api is nearly finalize. 

Since this PR is mainly handling IOS only (add a new param: `option`), and is no-op for android.

**Comment by zxcpoiu** [comment]
@sboily 

I've checked #251 a bit, you've added a `hasVideo`  in `displayIncomingCall` for pass to android. And the rest ios only options may now supported on Android.

This is current api for `displayIncomingCall` in this PR

```
displayIncomingCall = (uuid, handle, localizedCallerName = '', handleType = 'number', hasVideo = false, options = null)

- `options`: object (optional)
  - `ios`: object
    - `supportsHolding`: boolean (optional, default true)
    - `supportsDTMF`: boolean (optional, default true)
    - `supportsGrouping`: boolean (optional, default true)
    - `supportsUngrouping`: boolean (optional, default true)
```

### So I guess we need to:

* move ios only `handleType` to the option ( that's breaking change, but normalize the api ) 

### And for `updateDisplay = (uuid, displayName, handle, options = null)`

* `hasVideo` is already in optional arg `options`,  it's fine.

### And for both api:

* android add `options` args like in ios, but leave it no-op, when some android features has been implemented, then pass it to the native side



Does this what you mean?

**Comment by zxcpoiu** [comment]
rebased :wink:

**Review by manuquentin — APPROVED** [review]

**Comment by manuquentin** [comment]
Thanks @zxcpoiu !

**Comment by grit96** [comment]
Any chance we could follow semver when including breaking changes like this in releases? It was included in `3.1.5` but should really have been `4.0.0` due to the breaking `reportNewIncomingCall` API change.

**Comment by grit96** [comment]
Also, on `3.1.5` I am getting a crash on iOS after updating the `reportNewIncomingCall` call to match the new signature.

```
      NSString *uuid = [[[NSUUID UUID] UUIDString] lowercaseString];
      [RNCallKeep reportNewIncomingCall:uuid
                                 handle:@""
                             handleType:@"generic"
                               hasVideo:NO
                    localizedCallerName:@""
                        supportsHolding:YES
                           supportsDTMF:YES
                       supportsGrouping:NO
                     supportsUngrouping:NO
                            fromPushKit:YES
                                payload:nil
                  withCompletionHandler:completion];
```

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[RNCallKeep reportNewIncomingCall:handle:handleType:hasVideo:localizedCallerName:supportsHolding:supportsDTMF:supportsGrouping:supportsUngrouping:fromPushKit:payload:withCompletionHandler:]: unrecognized selector sent to class 0x10466ca00'
```

**Pull request merged**
