### PR TITLE
Allow non numbers and android video

### PR DESCRIPTION
**Pull request by danjenkins**
This branch needs updating in numerous ways and split out

Making a draft PR to discuss those things

### CODE REVIEW

**Comment by manuquentin** [comment]
Can we close this PR as it seem to be continued in #237 ?

**Comment by sboily** [comment]
Hello @danjenkins, i made a PR for a first works on video support. Check #251. I don't understand why we need to keep this PR. What is the main target of this PR. The #237 is to supported self managed capability. Can we rename this PR to reflect what we want to achieve? Thank you.

**Comment by sboily** [comment]
Yes yes i remember ;), thank you for this first work! A new PR with to support non numbers (sip uris) will be nice. Thank you!

**Review by HarshitPadalia — COMMENTED** [review]
Hello is there any plan to merge this to main branch?

**Comment by HarshitPadalia** [comment]
or let me know you are facing any issues. so I can help to shoutout any problems you. are facing

**Pull request closed without merging**
