### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by berdimyradov**
Updated index.d.ts in order to resolve bunch of 
`An implementation cannot be declared in ambient contexts.` typescript-errors

### CODE REVIEW

**Comment by manuquentin** [comment]
Thanks @berdimyradov, can you reformat your commit with 2 spaces indentation instead of 4 please?
It'll match the rest of the project indentation.

**Comment by berdimyradov** [comment]
> Thanks @berdimyradov, can you reformat your commit with 2 spaces indentation instead of 4 please?
> It'll match the rest of the project indentation.

**Comment by berdimyradov** [comment]
@manuquentin Thanks for noticing 🙏
Updated indenting

**Comment by manuquentin** [comment]
Thanks @berdimyradov !

**Pull request merged**
