### PR TITLE
Exposed the method reportEndCallWithUUID to handle a cancel VoIP Push Notification to tears down an incoming call

### PR DESCRIPTION
**Pull request by mariouzae**
Hi,

I expose the method **reportEndCallWithUUID** for those who want to cancel an incoming call using a Push Notification on iOS. Does anyone think it's useful for most?

thanks,

Mario

### CODE REVIEW

**Comment by manuquentin** [comment]
Thanks @mariouzae, can you rebase your PR ?

**Comment by mariouzae** [comment]
Hi @manuquentin , done!

thanks.

**Comment by ajnozari** [comment]
Question, should the push notification to end the call come over regular push or should it also be a VOIP Push?

**Comment by mariouzae** [comment]
I believe it is better to use regular push notification(background silent), Apple says if you don't report an incoming call screen many times, the APN's could stop sending the VoIP PN.

[https://developer.apple.com/documentation/pushkit/pkpushregistrydelegate/2875784-pushregistry?language=objc#discussion](url)

If you are using the project "react-native-voip-push-notification" look at this part of the doc:

[https://github.com/react-native-webrtc/react-native-voip-push-notification#important-note](url)

**Comment by ajnozari** [comment]
So I tried going that route, but while the incoming call ui is being displayed but no new notifications are being received. I'm using RNFirebse, do I need to intercept the message in my AppDelegate.m and look for the specific notification to cancel the call?

**Comment by mariouzae** [comment]
Yes, if you want to close the incoming call ui for some reason, you must handle this "cancel pn" in the ApplDelegate.m to close the incoming call. In my case, if the app receives an incoming call but it doesn't get registered on the server, I send this "cancel pn" to close the incoming call which I've created on the AppDelegate.

**Comment by ajnozari** [comment]
@mariouzae thank you for your help, I ended up following you and exposed a method to check if the current call is the active call. I'm submitting a PR in case it helps others. However it is IOS only as it utilizes the CXCallObserver and like checkIfBusy it is an IOS only method. I went ahead and exposed it React Native as well.

This way you can intercept the Push notification and trigger the UI to cancel the incoming call but only if you're not actively in the call.

**Pull request merged**
