### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by sambegin**
Fixed the startCall optional arg

### CODE REVIEW

**Comment by manuquentin** [comment]
thx !

**Comment by sambegin** [comment]
@manuquentin  How often are you releasing new versions for that kind of thing? Can we expect to have it updated in a 2.0.3 version soon? 
Thanks!

**Comment by sboily** [comment]
Yes we can do it today.

**Comment by manuquentin** [comment]
Hi @sambegin,
I've released a `2.0.3` with you fix.

**Comment by sambegin** [comment]
Thank you !

**Pull request merged**
