### PR TITLE
Start a foreground service to be able to get audio on Android 11 bg

### PR DESCRIPTION
**Pull request by manuquentin**
Refs #274

Thanks @grit96 for the patch !

Review/feedback are welcome for this one.

### CODE REVIEW

**Comment by sboily** [comment]
This issue is only if you compile your application with the android 11 SDK. Are you agree @manuquentin?

**Comment by sboily** [comment]
I made test and if i'm using my application with the SDK 29 on my android 11, i have no issue. But if i compile with the SDK 30, i reproduce this issue.

**Comment by grit96** [comment]
I just tested this and reproduce the issue against both SDK 29 and SDK 30 on Android 11 (Pixel 4).

**Comment by sboily** [comment]
Strange i don't reproduce that. My application works without any issues on pixel 3 and 5 with old SDK.

**Comment by grit96** [comment]
Yes it is strange. I ditched my patch and ran my app with this branch and it works well! The only suggestion I'd add is the ability to specify a notification icon.

**Comment by sboily** [comment]
Ok well, my mistake, i receive the audio, but nothing go out from the app!

**Comment by sboily** [comment]
@grit96 have you tried with this PR? Is it ok for you?

**Comment by grit96** [comment]
@sboily yes, tested the PR and it works.

I think we need to use `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {` because foreground services are only needed on SDK 28 and above (https://developer.android.com/guide/components/foreground-services).

I also suggested adding the ability to set the notification icon.

**Comment by manuquentin** [comment]
Thanks @grit96 I've added a check on the Android version and added the ability to set the smallIcon (not tested as I don't see the notification on Pixel 3...)
@sboily has tested it. If you're OK with it we can merge this PR

**Comment by grit96** [comment]
Thanks @manuquentin, it works great! I guess the only thing left is to add docs for the icon.

**Pull request merged**
