### PR TITLE
[Discuss] ios 13 handle voip incoming push notification

### PR DESCRIPTION
**Pull request by r0b0t3d**
With ios 13, apple has changed the flow we handle voip incoming push notification. 

> Important
On iOS 13.0 and later, incoming Voice over IP calls must be reported when they are received and before this method finishes execution using the CallKit framework, or the system will terminate your app. Repeatedly failing to report calls may prevent your app from receiving any more incoming call notifications.

https://developer.apple.com/documentation/pushkit/pkpushregistrydelegate/2875784-pushregistry

I update code to allow calling displayIncomingCall while handling voip push
```
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(NSString *)type {
  // Process the received push
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
  [[RNCallKeep sharedInstance] displayIncomingCall:uuid handle:@"handle" handleType:@"generic" hasVideo:true localizedCallerName:@"caller name"];
}
```
If you have any idea how to solve this problem, please let me know

[https://github.com/react-native-webrtc/react-native-voip-push-notification/issues/36](react-native-voip-push-notification/issues/36)

### CODE REVIEW

**Comment by manuquentin** [comment]
Hi @r0b0t3d, why did you close this issue ? Isn't it relevant anymore ?

**Comment by r0b0t3d** [comment]
I need more time to test. Will open another PR if everything is ok

**Comment by redexp** [comment]
@r0b0t3d I'm sorry, did you have any time to test this issue?

**Comment by r0b0t3d** [comment]
@redexp This issue has been merged on another PR. Please check #86

**Pull request closed without merging**
