### PR TITLE
Add setting for including calls in recents

### PR DESCRIPTION
**Pull request by mcorner**

### CODE REVIEW

**Comment by mcorner** [comment]
Correct.

**Comment by kylekurz** [comment]
I like this as a configurable option, great work @mcorner.

**Comment by kylekurz** [comment]
@mcorner can you rebase off master to fix the conflicts so this can merge?

**Comment by manuquentin** [comment]
ping @mcorner can you rebase this PR ?

**Comment by mcorner** [comment]
Sorry, we moved off of this project.  Happy to close it.

**Pull request closed without merging**
